[package]
name = "tlsum"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
opt-level = "z"

[dependencies]
anyhow = "1.0.57"
itertools = "0.10.3"
thiserror = "1.0.30"
time = { version = "0.3.9", features = ["macros", "parsing", "local-offset", "formatting"] }
